/** IPC channel names + API surface shared via preload */

export const IPC = {
  APP_GET_STATUS: 'app:get-status',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SCHEMAS_LIST: 'schemas:list',
  SCHEMAS_GET: 'schemas:get',
  SCHEMAS_SAVE: 'schemas:save',
  SCHEMAS_DELETE: 'schemas:delete',
  SCHEMAS_TOUCH_OPENED: 'schemas:touch-opened',
  SCHEMAS_IMPORT: 'schemas:import',
  SCHEMAS_IMPORT_PICK: 'schemas:import-pick',
  TEMPLATES_LIST: 'templates:list',
  TEMPLATES_SAVE: 'templates:save',
  TEMPLATES_DELETE: 'templates:delete',
  HISTORY_LIST: 'history:list',
  HISTORY_PAGE: 'history:page',
  HISTORY_SUGGEST: 'history:suggest',
  HISTORY_KEYS: 'history:keys',
  HISTORY_RECORD: 'history:record',
  HISTORY_RECORD_MANY: 'history:record-many',
  HISTORY_CLEAR: 'history:clear',
  HISTORY_CLEAR_COUNT: 'history:clear-count',
  HISTORY_DELETE: 'history:delete',
  HISTORY_UPDATE: 'history:update',
  HISTORY_DELETE_MATCHING: 'history:delete-matching',
  INTERACTION_LOG: 'interaction:log',
  GENERATE: 'generate:run',
  GENERATE_STREAM: 'generate:stream',
  GENERATE_PROGRESS: 'generate:progress',
  MANIFEST_PICK: 'manifest:pick',
  MANIFEST_PREVIEW: 'manifest:preview',
  EXPORT_FILE: 'export:file',
  EXPORT_ARCHIVE: 'export:archive',
  ENCRYPTION_STATUS: 'encryption:status',
  ENCRYPTION_SAVE_SCRIPT: 'encryption:save-script',
  ENCRYPTION_SAVE_KEY: 'encryption:save-key',
  ENCRYPTION_PICK_SCRIPT: 'encryption:pick-script',
  ENCRYPTION_PICK_KEY: 'encryption:pick-key',
  ENCRYPTION_CLEAR_SCRIPT: 'encryption:clear-script',
  ENCRYPTION_CLEAR_KEY: 'encryption:clear-key',
  ENCRYPTION_TEST: 'encryption:test',
  CACHE_REFRESH: 'cache:refresh',
  BACKUP_EXPORT: 'backup:export',
  BACKUP_IMPORT: 'backup:import'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
