"""
Starter theme packs shipped with DataForge.

Seeded into SQLite on first run (and when seed version bumps). Uses stable IDs
and INSERT OR IGNORE so user-added categories/values are never wiped, and
re-running seed does not duplicate rows.
"""
from __future__ import annotations

from typing import Any

# Bump when adding packs or expanding default pools so installs pick up new data.
BUILTIN_THEMES_SEED_VERSION = 1

# Stable IDs so reinstall / re-seed stays deterministic across machines.
_GENERAL_ID = "theme-builtin-general"
_STAR_WARS_ID = "theme-builtin-star-wars"
_FANTASY_ID = "theme-builtin-fantasy"

# category -> list of values (keep well under MAX_THEME_CATEGORY_VALUES=100)
BUILTIN_THEME_PACKS: list[dict[str, Any]] = [
    {
        "id": _GENERAL_ID,
        "name": "General",
        "slug": "general",
        "description": "Everyday names, places, and orgs for quick test data.",
        "isBuiltin": True,
        "categories": {
            "names": [
                "Alex Rivera",
                "Jordan Lee",
                "Sam Patel",
                "Casey Morgan",
                "Taylor Brooks",
                "Riley Quinn",
                "Morgan Blake",
                "Avery Chen",
                "Jamie Ortiz",
                "Cameron Walsh",
                "Harper Diaz",
                "Reese Nguyen",
                "Parker Singh",
                "Drew Alvarez",
                "Skyler Kim",
                "Quinn Foster",
                "Finley Hayes",
                "Rowan Price",
                "Emery Cole",
                "Sage Bennett",
            ],
            "first_names": [
                "Alex",
                "Jordan",
                "Sam",
                "Casey",
                "Taylor",
                "Riley",
                "Morgan",
                "Avery",
                "Jamie",
                "Cameron",
                "Harper",
                "Reese",
                "Parker",
                "Drew",
                "Skyler",
                "Quinn",
                "Finley",
                "Rowan",
                "Emery",
                "Sage",
            ],
            "last_names": [
                "Rivera",
                "Lee",
                "Patel",
                "Morgan",
                "Brooks",
                "Quinn",
                "Blake",
                "Chen",
                "Ortiz",
                "Walsh",
                "Diaz",
                "Nguyen",
                "Singh",
                "Alvarez",
                "Kim",
                "Foster",
                "Hayes",
                "Price",
                "Cole",
                "Bennett",
            ],
            "cities": [
                "Austin",
                "Seattle",
                "Denver",
                "Portland",
                "Chicago",
                "Boston",
                "Atlanta",
                "Phoenix",
                "Miami",
                "Dallas",
                "London",
                "Toronto",
                "Berlin",
                "Tokyo",
                "Sydney",
                "Dublin",
                "Amsterdam",
                "Singapore",
                "Montreal",
                "Lisbon",
            ],
            "countries": [
                "United States",
                "Canada",
                "United Kingdom",
                "Germany",
                "France",
                "Japan",
                "Australia",
                "Brazil",
                "India",
                "Mexico",
                "Spain",
                "Italy",
                "Netherlands",
                "Sweden",
                "Ireland",
            ],
            "companies": [
                "Northwind Labs",
                "Acme Analytics",
                "Blue Harbor Systems",
                "Cedar Peak Software",
                "Ironclad Data",
                "Lumen Field Tech",
                "Orbit Mesa Co",
                "Pinecrest Digital",
                "Riverstone Works",
                "Summit Ridge Inc",
                "Terra Nova Group",
                "Vertex Harbor",
                "Willow Creek Apps",
                "Zenith Parcel",
                "Brightline Ops",
            ],
            "streets": [
                "Main St",
                "Oak Ave",
                "Maple Dr",
                "Cedar Ln",
                "Pine Rd",
                "Elm St",
                "Lakeview Blvd",
                "Park Ave",
                "Hillcrest Way",
                "River Rd",
                "Sunset Blvd",
                "2nd Ave",
                "Market St",
                "Broadway",
                "Highland Ave",
            ],
            "statuses": [
                "active",
                "pending",
                "closed",
                "draft",
                "approved",
                "rejected",
                "archived",
                "in_review",
            ],
            "departments": [
                "Engineering",
                "Sales",
                "Support",
                "Finance",
                "Marketing",
                "Operations",
                "HR",
                "Legal",
                "Product",
                "Research",
            ],
        },
    },
    {
        "id": _STAR_WARS_ID,
        "name": "Star Wars",
        "slug": "star-wars",
        "description": "Genre pack — characters, ships, planets, and orders.",
        "isBuiltin": True,
        "categories": {
            "names": [
                "Luke Skywalker",
                "Leia Organa",
                "Han Solo",
                "Obi-Wan Kenobi",
                "Darth Vader",
                "Yoda",
                "Padmé Amidala",
                "Anakin Skywalker",
                "Ahsoka Tano",
                "Din Djarin",
                "Grogu",
                "Rey",
                "Finn",
                "Poe Dameron",
                "Kylo Ren",
                "Lando Calrissian",
                "Chewbacca",
                "R2-D2",
                "C-3PO",
                "Boba Fett",
                "Mace Windu",
                "Qui-Gon Jinn",
                "Count Dooku",
                "Palpatine",
                "Jabba the Hutt",
            ],
            "ships": [
                "Millennium Falcon",
                "X-Wing",
                "TIE Fighter",
                "Star Destroyer",
                "Slave I",
                "Razor Crest",
                "Ghost",
                "Naboo Royal Starship",
                "A-Wing",
                "Y-Wing",
                "Lambda Shuttle",
                "Death Star",
                "Executor",
                "Tantive IV",
                "Nebulon-B Frigate",
            ],
            "planets": [
                "Tatooine",
                "Hoth",
                "Endor",
                "Dagobah",
                "Coruscant",
                "Naboo",
                "Alderaan",
                "Mustafar",
                "Kamino",
                "Geonosis",
                "Jakku",
                "Kashyyyk",
                "Mandalore",
                "Bespin",
                "Yavin 4",
            ],
            "species": [
                "Human",
                "Wookiee",
                "Twi'lek",
                "Rodian",
                "Trandoshan",
                "Hutt",
                "Zabrak",
                "Togruta",
                "Mon Calamari",
                "Gungan",
            ],
            "orders": [
                "Jedi Order",
                "Sith",
                "Rebel Alliance",
                "Galactic Empire",
                "New Republic",
                "First Order",
                "Mandalorians",
                "Bounty Hunters Guild",
            ],
        },
    },
    {
        "id": _FANTASY_ID,
        "name": "Fantasy",
        "slug": "fantasy",
        "description": "Heroes, realms, and relics for RPG-style test data.",
        "isBuiltin": True,
        "categories": {
            "names": [
                "Aria Stormwind",
                "Thorne Blackwood",
                "Lyra Silverleaf",
                "Gareth Ironhelm",
                "Elowen Brightspear",
                "Kael Nightbloom",
                "Seraphine Vale",
                "Dorian Ashford",
                "Mirabel Frost",
                "Rowan Thorn",
                "Isolde Raven",
                "Cedric Oakenshield",
                "Faye Moonwhisper",
                "Alaric Stone",
                "Nyx Emberfall",
            ],
            "realms": [
                "Eldermoor",
                "Silverreach",
                "Dragonspine",
                "Mistvale",
                "Ironmarch",
                "Starfall Coast",
                "The Whispering Woods",
                "Sunken Kingdom",
                "Highcrown",
                "Shadowfen",
                "Crystalmere",
                "Frostpeak",
            ],
            "creatures": [
                "Dragon",
                "Griffin",
                "Phoenix",
                "Unicorn",
                "Basilisk",
                "Dire Wolf",
                "Kraken",
                "Wyvern",
                "Sprite",
                "Golem",
            ],
            "items": [
                "Moonblade",
                "Amulet of Wards",
                "Scroll of Binding",
                "Starforged Shield",
                "Potion of Clarity",
                "Ring of Echoes",
                "Staff of Embers",
                "Cloak of Mists",
                "Crown of Thorns",
                "Map of Lost Roads",
            ],
            "factions": [
                "Order of the Lantern",
                "Ashen Compact",
                "Circle of Nine",
                "Free Companies",
                "Tideborn Fleet",
                "Wardens of the Vale",
                "Crimson Court",
                "Stone Guardians",
            ],
        },
    },
]


def all_seed_value_count() -> int:
    n = 0
    for pack in BUILTIN_THEME_PACKS:
        for vals in (pack.get("categories") or {}).values():
            n += len(vals or [])
    return n
